project:
  type: website
website:
  title: jarl
  navbar:
    search: true
    left:
    - text: Home
      href: index.qmd
    - text: Rules
      href: rules.qmd
    - text: Development
      href: development.qmd
    - text: About
      href: about.qmd
  sidebar:
  - title: Rules
    style: docked
    background: light
    contents:
    - rules.qmd
    - rules/any_duplicated.qmd
    - rules/any_is_na.qmd
    - rules/assignment.qmd
    - rules/class_equals.qmd
    - rules/duplicated_arguments.qmd
    - rules/equals_na.qmd
    - rules/for_loop_index.qmd
    - rules/grepv.qmd
    - rules/is_numeric.qmd
    - rules/length_levels.qmd
    - rules/length_test.qmd
    - rules/lengths.qmd
    - rules/matrix_apply.qmd
    - rules/redundant_equals.qmd
    - rules/sample_int.qmd
    - rules/sort.qmd
    - rules/true_false_symbol.qmd
    - rules/which_grepl.qmd
